name: 'Create Version Tag And Release'
description: 'Create a new release with calendar versioning'
inputs:
  owner:  # id of input
    description: 'Account owner'
    required: true
    default: ''
  repo:
    description: 'Repository name'
    required: true
    default: ''
  myToken:
    description: 'Github Token'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
